name: TotemCooldown
main: space.wtnpmt.mcplugin.TCD.TotemCooldown
version: 0.2.0
api: "1.13"
authors: [pumpkin_pmt]
permissions:
  totemcooldown.disable:
    default: false
    description: disable cooldown.
commands:
  totemcooldown:
    description: TotemCooldown commands.
    usage: /<command> <gettime/settime [time]>
    permission: totemcooldown.command